[versions]
agp = "9.0.0"
androidxAppcompat = "1.6.1"
appcompatVersion = "1.7.0"
billing = "8.3.0"
billingVersion = "6.1.0"
constraintlayoutVersion = "2.1.4"
geo = "0.8.1"
googleMaterial = "1.11.0"
googleMaterialVersion = "1.13.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kosherjavaZmanim = "2.6.0"
latlongtotimezone = "VERSION"
material = "1.12.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
materialVersion = "1.12.0"
netTimeshape = "2023a.10"
playServicesLocation = "21.3.0"
playServicesLocationVersion = "21.0.1"
timeshape = "2025b.28"
timeshapeVersion = "2025b.26"
timezoneMap = "1.0.0"
timezonemapBuilder = "4.5"
timezonemapUtils = "3.4"
timezoneMapVersion = "0.3"
workRuntimeVersion = "2.9.0"
zmanim = "2.5.0"
zmanimVersion = "1.15"
zstdJni = "1.5.7-6"
workRuntime = "2.11.0"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
billing-v610 = { module = "com.android.billingclient:billing", version.ref = "billingVersion" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
geo = { module = "com.github.davidmoten:geo", version.ref = "geo" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
latlongtotimezone = { module = "com.github.MartinsThiago:LatLongToTimezone", version.ref = "latlongtotimezone" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v1130 = { module = "com.google.android.material:material", version.ref = "googleMaterialVersion" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
timeshape = { module = "net.iakovlev:timeshape", version.ref = "timeshape" }
timeshape-v2023a10 = { module = "net.iakovlev:timeshape", version.ref = "netTimeshape" }
timeshape-v2025b26 = { module = "net.iakovlev:timeshape", version.ref = "timeshapeVersion" }
timezone-map = { module = "com.github.mik3y:timezone-map", version.ref = "timezoneMap" }
timezone-map-v03 = { module = "com.github.mik3y:timezone-map", version.ref = "timezoneMapVersion" }
timezonemap-builder = { module = "us.dustinj.timezonemap:timezonemap-builder", version.ref = "timezonemapBuilder" }
timezonemap-data = { module = "us.dustinj.timezonemap:timezonemap-data", version.ref = "timezonemapBuilder" }
timezonemap-utils = { module = "us.dustinj.timezonemap:timezonemap-utils", version.ref = "timezonemapUtils" }
work-runtime-v290 = { module = "androidx.work:work-runtime", version.ref = "workRuntimeVersion" }
zmanim = { module = "com.kosherjava:zmanim", version.ref = "zmanim" }
zmanim-v115 = { module = "com.kosherjava:zmanim", version.ref = "zmanimVersion" }
zmanim-v260 = { module = "com.kosherjava:zmanim", version.ref = "kosherjavaZmanim" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstdJni" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

